### ISSUE TITLE
TS declarations not included in build

### ISSUE THREAD

**Issue by will-hart** [endel/ecs#1]
When importing into a project, VS code reports

```
Cannot find module '@colyseus/ecs' or its corresponding type declarations.ts(2307)
```

Looking at the `@colyseus/ecs` folder in the node_modules there are no declarations in `/lib/index.d.ts`

**Comment by endel** [comment]
Hi @will-hart, 👋  glad you're trying this out early. I've just published the latest version with typings included

Beware things might not be very stable - both at the ECSY integration and the new `@colyseus/schema` version. I'm currently trying to understand the cause of a `"refId" not found: xxx` that happens sometimes in the latest `@colyseus/schema` version.

Feel free to poke me here or on Discord if you have any feedback to give!
Cheers!

**Comment by will-hart** [comment]
Awesome, thanks!

Yes, I saw it was an experiment. I've been playing around with my own ECS to integrate with colyseus, but was struggling to cleanly sync `ECS >> server schema --> client schema >> ECS`.

I think your approach here looks promising!
